xcopy /Y/S ..\..\djondb\db\buildx64\bson\Release\djon-bson.lib djondb_csharp\libs\Release\x64
xcopy /Y/S ..\..\djondb\db\buildx64\cache\Release\djon-cache.lib djondb_csharp\libs\Release\x64
xcopy /Y/S ..\..\djondb\db\buildx64\driverbase\Release\djon-client.lib djondb_csharp\libs\Release\x64
xcopy /Y/S ..\..\djondb\db\buildx64\driverbase\Release\djon-clientStatic.lib djondb_csharp\libs\Release\x64
xcopy /Y/S ..\..\djondb\db\buildx64\command\Release\djon-command.lib djondb_csharp\libs\Release\x64
xcopy /Y/S ..\..\djondb\db\buildx64\db\Release\djon-db.lib djondb_csharp\libs\Release\x64
xcopy /Y/S ..\..\djondb\db\buildx64\filesystem\Release\djon-filesystem.lib djondb_csharp\libs\Release\x64
xcopy /Y/S ..\..\djondb\db\buildx64\network\Release\djon-network.lib djondb_csharp\libs\Release\x64
xcopy /Y/S ..\..\djondb\db\buildx64\service\Release\djon-service.lib djondb_csharp\libs\Release\x64
xcopy /Y/S ..\..\djondb\db\buildx64\tx\Release\djon-tx.lib djondb_csharp\libs\Release\x64
xcopy /Y/S ..\..\djondb\db\buildx64\util\Release\djon-util.lib djondb_csharp\libs\Release\x64

xcopy /Y/S ..\..\djondb\db\buildWin32\bson\Release\djon-bson.lib djondb_csharp\libs\Release\Win32
xcopy /Y/S ..\..\djondb\db\buildWin32\cache\Release\djon-cache.lib djondb_csharp\libs\Release\Win32
xcopy /Y/S ..\..\djondb\db\buildWin32\driverbase\Release\djon-client.lib djondb_csharp\libs\Release\Win32
xcopy /Y/S ..\..\djondb\db\buildWin32\driverbase\Release\djon-clientStatic.lib djondb_csharp\libs\Release\Win32
xcopy /Y/S ..\..\djondb\db\buildWin32\command\Release\djon-command.lib djondb_csharp\libs\Release\Win32
xcopy /Y/S ..\..\djondb\db\buildWin32\db\Release\djon-db.lib djondb_csharp\libs\Release\Win32
xcopy /Y/S ..\..\djondb\db\buildWin32\filesystem\Release\djon-filesystem.lib djondb_csharp\libs\Release\Win32
xcopy /Y/S ..\..\djondb\db\buildWin32\network\Release\djon-network.lib djondb_csharp\libs\Release\Win32
xcopy /Y/S ..\..\djondb\db\buildWin32\service\Release\djon-service.lib djondb_csharp\libs\Release\Win32
xcopy /Y/S ..\..\djondb\db\buildWin32\tx\Release\djon-tx.lib djondb_csharp\libs\Release\Win32
xcopy /Y/S ..\..\djondb\db\buildWin32\util\Release\djon-util.lib djondb_csharp\libs\Release\Win32
