xcopy /Y/S ..\..\djondb_0.34\db\buildx64\bson\RelWithDebInfo\djon-bson.lib djondb_csharp\libs\RelWithDebInfo\x64
xcopy /Y/S ..\..\djondb_0.34\db\buildx64\cache\RelWithDebInfo\djon-cache.lib djondb_csharp\libs\RelWithDebInfo\x64
xcopy /Y/S ..\..\djondb_0.34\db\buildx64\driverbase\RelWithDebInfo\djon-client.lib djondb_csharp\libs\RelWithDebInfo\x64
xcopy /Y/S ..\..\djondb_0.34\db\buildx64\driverbase\RelWithDebInfo\djon-clientStatic.lib djondb_csharp\libs\RelWithDebInfo\x64
xcopy /Y/S ..\..\djondb_0.34\db\buildx64\command\RelWithDebInfo\djon-command.lib djondb_csharp\libs\RelWithDebInfo\x64
xcopy /Y/S ..\..\djondb_0.34\db\buildx64\db\RelWithDebInfo\djon-db.lib djondb_csharp\libs\RelWithDebInfo\x64
xcopy /Y/S ..\..\djondb_0.34\db\buildx64\filesystem\RelWithDebInfo\djon-filesystem.lib djondb_csharp\libs\RelWithDebInfo\x64
xcopy /Y/S ..\..\djondb_0.34\db\buildx64\network\RelWithDebInfo\djon-network.lib djondb_csharp\libs\RelWithDebInfo\x64
xcopy /Y/S ..\..\djondb_0.34\db\buildx64\service\RelWithDebInfo\djon-service.lib djondb_csharp\libs\RelWithDebInfo\x64
xcopy /Y/S ..\..\djondb_0.34\db\buildx64\tx\RelWithDebInfo\djon-tx.lib djondb_csharp\libs\RelWithDebInfo\x64
xcopy /Y/S ..\..\djondb_0.34\db\buildx64\util\RelWithDebInfo\djon-util.lib djondb_csharp\libs\RelWithDebInfo\x64

xcopy /Y/S ..\..\djondb_0.34\db\buildWin32\bson\RelWithDebInfo\djon-bson.lib djondb_csharp\libs\RelWithDebInfo\Win32
xcopy /Y/S ..\..\djondb_0.34\db\buildWin32\cache\RelWithDebInfo\djon-cache.lib djondb_csharp\libs\RelWithDebInfo\Win32
xcopy /Y/S ..\..\djondb_0.34\db\buildWin32\driverbase\RelWithDebInfo\djon-client.lib djondb_csharp\libs\RelWithDebInfo\Win32
xcopy /Y/S ..\..\djondb_0.34\db\buildWin32\driverbase\RelWithDebInfo\djon-clientStatic.lib djondb_csharp\libs\RelWithDebInfo\Win32
xcopy /Y/S ..\..\djondb_0.34\db\buildWin32\command\RelWithDebInfo\djon-command.lib djondb_csharp\libs\RelWithDebInfo\Win32
xcopy /Y/S ..\..\djondb_0.34\db\buildWin32\db\RelWithDebInfo\djon-db.lib djondb_csharp\libs\RelWithDebInfo\Win32
xcopy /Y/S ..\..\djondb_0.34\db\buildWin32\filesystem\RelWithDebInfo\djon-filesystem.lib djondb_csharp\libs\RelWithDebInfo\Win32
xcopy /Y/S ..\..\djondb_0.34\db\buildWin32\network\RelWithDebInfo\djon-network.lib djondb_csharp\libs\RelWithDebInfo\Win32
xcopy /Y/S ..\..\djondb_0.34\db\buildWin32\service\RelWithDebInfo\djon-service.lib djondb_csharp\libs\RelWithDebInfo\Win32
xcopy /Y/S ..\..\djondb_0.34\db\buildWin32\tx\RelWithDebInfo\djon-tx.lib djondb_csharp\libs\RelWithDebInfo\Win32
xcopy /Y/S ..\..\djondb_0.34\db\buildWin32\util\RelWithDebInfo\djon-util.lib djondb_csharp\libs\RelWithDebInfo\Win32
